name: update_service_provider

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update on service provider
        run: curl http://http://unn4m3dd.xyz//update?repo=Jogos-Retro-em-HTML
